version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: todo-app-db
    environment:
      MYSQL_ROOT_PASSWORD: 00000000
      MYSQL_USER: root
      MYSQL_PASSWORD: 00000000
      MYSQL_DATABASE: todo_app_db
    ports:
      - '3312:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: no
volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
